### ISSUE TITLE
API Proxy Address

### ISSUE THREAD

**Issue by comeback01** [Zaki-1052/GPTPortal#19]
Hello,

I use another program that allows to customize "API Proxy Address", for OpenAI and Anthropic.

They also allow custom AI endpoints, if they are OpenIA compatible.

Do you plan to do the same.

Thanks

**Comment by Zaki-1052** [comment]
I'm not sure if you mean [this one](https://github.com/nephen/simple-openai-api-proxy) or [reverse proxy](https://github.com/PawanOsman/ChatGPT), but both seem sketchy and I would not recommend. 

Alternatively, if you're just talking about [OpenRouter](https://openrouter.ai/docs), then there are simply far too many models to account for a separate endpoint and it would require a major refactor of how requests are currently made. Additionally, I wouldn't trust all of my API requests to be routed through a closed-source company that want you to use _their_ URL.

**Answer**: Not currently planned; I don't personally use nor trust it, and they expect different JSON formats depending on the API model, so it would be impractical to add new models as they come out. For OpenAI and Anthropic, as they're currently both directly supported through their APIs, I would recommend following the official process there. You can replace the Mistral endpoint with the OpenAPI endpoint if you'd like in `server.js`, since it uses the same code format; otherwise not likely.

**Comment by comeback01** [comment]
What I mean is that instead of https://api.openai.com, put the url of OpenRouteur or others to use GPT or clande, or mistal.

For example, I'm in Europe and I don't have access to Claude!

If I take LibreChat as an example, it lists the available templates using the address https://xxx.xxx.com/v1/models.

Again, this isn't what I want, but I want to be able to use other providers for GPT and, if possible, Claude.

Thanks for your help

https://docs.librechat.ai/install/configuration/ai_endpoints.html#ollama
